# Generated by Django 5.1.3 on 2025-01-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
